export const SUSTAINABILITY_TIPS = [
  'Switch off appliances when not in use.',
  'Walk for short distances instead of driving.',
  'Use reusable bags when shopping.',
  'Reduce food waste by planning meals ahead.',
  'Switch to LED bulbs to save energy.',
  'Take public transport whenever possible.',
  'Unplug chargers when not in use.',
  'Buy local and seasonal produce.',
  'Fix leaks to save water and energy.',
  'Compost organic waste at home.',
  'Use a refillable water bottle.',
  'Air dry clothes instead of using a dryer.',
];

export const REDUCTION_TIPS = [
  {
    id: 'public-transport',
    title: 'Use Public Transport',
    description: 'Switch to buses or metro for daily commute to cut emissions significantly.',
    icon: 'Bus',
  },
  {
    id: 'led-lights',
    title: 'Switch to LED Lights',
    description: 'LED bulbs use up to 75% less energy than incandescent bulbs.',
    icon: 'Lightbulb',
  },
  {
    id: 'solar-panels',
    title: 'Install Solar Panels',
    description: 'Generate clean energy and reduce grid electricity dependency.',
    icon: 'Sun',
  },
  {
    id: 'reduce-food-waste',
    title: 'Reduce Food Waste',
    description: 'Plan meals and store food properly to minimize waste.',
    icon: 'Apple',
  },
  {
    id: 'recycle',
    title: 'Recycle',
    description: 'Separate and recycle paper, plastic, and metal waste.',
    icon: 'Recycle',
  },
  {
    id: 'plant-trees',
    title: 'Plant Trees',
    description: 'Trees absorb CO2 and improve air quality in your community.',
    icon: 'TreePine',
  },
];

export const EDUCATION_CONTENT = {
  title: 'What is Carbon Footprint?',
  description:
    'A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) generated by our actions. It is measured in tonnes of CO2 equivalent per year.',
  whyItMatters:
    'India is the third-largest emitter globally. Understanding your footprint helps combat climate change, protect biodiversity, and build a sustainable future for generations.',
};

export const EMISSION_SOURCES = [
  {
    id: 'transportation',
    title: 'Transportation',
    description: 'Cars, buses, trains, and flights contribute significantly to personal emissions.',
    icon: 'Car',
  },
  {
    id: 'electricity',
    title: 'Electricity Consumption',
    description: 'Power generation from coal and gas releases large amounts of CO2.',
    icon: 'Zap',
  },
  {
    id: 'food',
    title: 'Food Production',
    description: 'Agriculture, especially meat production, generates substantial greenhouse gases.',
    icon: 'UtensilsCrossed',
  },
  {
    id: 'waste',
    title: 'Waste Generation',
    description: 'Landfills produce methane, a potent greenhouse gas.',
    icon: 'Trash2',
  },
];

export const ENVIRONMENTAL_IMPACTS = [
  {
    id: 'global-warming',
    title: 'Global Warming',
    description: 'Rising temperatures affect ecosystems and weather patterns worldwide.',
    icon: 'ThermometerSun',
  },
  {
    id: 'climate-change',
    title: 'Climate Change',
    description: 'Long-term shifts in temperature and weather patterns disrupt livelihoods.',
    icon: 'CloudRain',
  },
  {
    id: 'deforestation',
    title: 'Deforestation',
    description: 'Forests are cleared for agriculture, reducing CO2 absorption capacity.',
    icon: 'Trees',
  },
  {
    id: 'air-pollution',
    title: 'Air Pollution',
    description: 'Burning fossil fuels releases harmful pollutants affecting health.',
    icon: 'Wind',
  },
  {
    id: 'biodiversity',
    title: 'Biodiversity Loss',
    description: 'Species extinction accelerates as habitats are destroyed by climate change.',
    icon: 'Bug',
  },
  {
    id: 'extreme-weather',
    title: 'Extreme Weather Events',
    description: 'More frequent floods, droughts, and cyclones threaten communities.',
    icon: 'CloudLightning',
  },
];

export const CALCULATION_CATEGORIES = [
  { id: 'electricity', title: 'Household Electricity', icon: 'Zap', unit: 'kWh/month' },
  { id: 'transportation', title: 'Transportation', icon: 'Car', unit: 'km/month' },
  { id: 'flights', title: 'Flights', icon: 'Plane', unit: 'flights/year' },
  { id: 'food', title: 'Food Habits', icon: 'UtensilsCrossed', unit: 'diet type' },
  { id: 'waste', title: 'Waste Generation', icon: 'Trash2', unit: 'kg/week' },
];

export const SUSTAINABILITY_STATS = [
  {
    id: 'indian-average',
    label: 'Average Indian Annual Footprint',
    value: '1.9',
    unit: 'tonnes CO₂/year',
    icon: 'Users',
  },
  {
    id: 'global-emissions',
    label: 'Global Annual Emissions',
    value: '36',
    unit: 'billion tonnes CO₂',
    icon: 'Globe',
  },
  {
    id: 'trees-required',
    label: 'Trees to Absorb 1 Tonne CO₂',
    value: '48',
    unit: 'trees/year',
    icon: 'TreePine',
  },
  {
    id: 'top-contributor',
    label: 'Major Emission Contributor',
    value: 'Energy',
    unit: '73% of emissions',
    icon: 'Flame',
  },
];
